### ISSUE TITLE
patch: code style

### ISSUE THREAD

**Issue by TheRealMarnes** [sblask/firefox-skip-redirect#1]
I've made a patch to improve code style as per https://github.com/mozilla/addon-sdk/wiki/Coding-style-guide

https://dl.dropboxusercontent.com/u/3357590/patch.diff

Feel free to ignore most of it, my actually functional changes are limited to changing if structures and boolean expressions to a more logical structure. I just wanted to write this patch as a way of showing interest in your addon: ever since Redirect Cleaner 3.0 disappeared there's been kind of a void that the existing addons just can't fill. Please ask me if you'd like another pair of hands to help :)

Sorry if this is the wrong place for a patch btw but I can't make a pull request

**Comment by sblask** [comment]
Thanks for the interest, but I think I will actually give most of it a pass. The coding style is only for sdk, not for add-ons. I might change to arrow functions and consts in some places, but I I don't have too much time for that at the moment. With regards to logical structures, I follow the Python Zen here, flat is better than nested. I also used a variable in one place to not have to use a comment.

What's the issue with pull requests, do I need to change some setting?

**Comment by TheRealMarnes** [comment]
Ah, ok, that's fine :)

The pull request wizard asks me to compare 2 branches, but since nobody has permissions to add a branch to your repo... I'm not sure how it's supposed to make sense, you can't just go around giving everyone branch permissions on your project :/ I just tried making a fork and committing to that, but the wizard only accepts branches of the source project.

**Comment by sblask** [comment]
That's weird, forking should be the way to do it and then pull request should just do the right thing. I don't do that often though, so no idea what to do exactly.
