### ISSUE TITLE
Make a thunderbird version

### ISSUE THREAD

**Issue by xuhdev** [sblask/firefox-skip-redirect#10]
I think it's pretty cool if it is also available for thunderbird...

**Comment by sblask** [comment]
You don't open links in Firefox?

**Comment by xuhdev** [comment]
I see what you are suggesting here, but the links in the mail are hard to view because of the redirection thing -- it is harder to, for example, search mails.

**Comment by sblask** [comment]
I think you misunderstood what this add-on is doing, links in a document are not actually changed. Only when a request to a URL is made, are hidden/encoded URLs extracted from the original URL and the request to that one made instead. So I don't think it would help for your use case.

**Comment by xuhdev** [comment]
@sblask Thanks, I see. It's good to know!
