### ISSUE TITLE
Permit archive services

### ISSUE THREAD

**Issue by wbt** [sblask/firefox-skip-redirect#12]
When a link points to an archive domain, such as web.archive.org, the add-on functionality should be disabled.  Sometimes, the web archive is being used because the original domain has been redirected to serve malware, or has otherwise changed in a pretty significant way, and this add-on prevents people from accessing archived versions (while it is enabled).

**Comment by sblask** [comment]
You can always create a list of your own exceptions in the preferences. I can't possibly add cases for all the exception. people come up with. I think the real way to fix it is implementing #2 but I haven't had the time yet.

**Comment by o-jasper** [comment]
So will exceptions have some things defaultly in there? Could simultaniously help as examples?

**Comment by sblask** [comment]
This is the default list: https://github.com/sblask/firefox-skip-redirect/blob/master/lib/url.js#L4 Basically a list of things that I found are likely to cause problems. It's not containing site-specific stuff. It's used here: https://github.com/sblask/firefox-skip-redirect/blob/master/lib/url.js#L124 So it's equally important as the list coming from the preference. A simple string match, so you can add `archive.org` or be more specific.
