### ISSUE TITLE
Slickdeals.net

### ISSUE THREAD

**Issue by Aromendal** [sblask/firefox-skip-redirect#14]
Thanks for your addon. Please be the first redirect skipping add-on to strip slickdeals.net's redirect links, it is desperately needed.

**Comment by sblask** [comment]
Can you give me an example link?

**Comment by Aromendal** [comment]
Hi sblask, here are a few random ones. The redirect process seems to vary depending on sites referred to (and those site's needs/process for tracking referrals and commissions to referral sites like slickdeals.net) Thanks for taking a look at it! 

https://slickdeals.net/?adobeRef=9d24ee201d5611e79c4756e88f83325f0001&pno=278320&lno=1&trd=Home%2BDepot&afsrc=1

https://slickdeals.net/?adobeRef=1ab9c8061d5711e7b27bf2c25c54a6070000&pno=278692&afsrc=1&trd=See+Deal&pv=1ac22d021d5711e7b27bf2c25c54a607&au=e7c4698c7c2f11e29f36aa980500b9fe

https://slickdeals.net/?adobeRef=32b6ddb81d5711e798b5fad51a7f68bf0002&pno=278584&lno=1&trd=ShoeBuy%2Bcom&afsrc=1

https://slickdeals.net/?adobeRef=5a9540261d5811e7922f7e5cd90b33c20001&pno=278596&lno=1&trd=Fox%2BConnect&afsrc=1

https://slickdeals.net/?adobeRef=79e365ca1d5811e797fa5a9a80c527680000&pno=278640&lno=4&trd=12oz%2BStarbucks%2BColombian%2BGround%2B&afsrc=1

**Comment by sblask** [comment]
These URLs don't seem to contain any encoded URLs - nothing I can do here!

**Comment by Aromendal** [comment]
Darn, that's too bad. They had some more standard redirect url's up until recently but seem to have been moving everything over to this new method lately. One can only imagine why...because they are harder to parse. Maybe someone will eventually come up with another approach to extract the end result from the trail of links and scripts that this method seems to take the user through (some trails longer than others.) Thanks for taking a look at it, sblask!

**Comment by kerframil** [comment]
Slickdeals referrals make use of HTTP/302 redirection. The URLs conveyed by the Location header seem generally easy to parse. I don't know whether handling this kind of redirection is within the scope of this add-on, though. Still, here are the six samples that were posted by the OP:

```
Location: http://www.jdoqocy.com/click-1225267-10368321?sid=c56ed2b422a211e788aa52b118366b510INT&url=http%3A%2F%2Fwww.homedepot.com%2Fp%2FLow-Voltage-1-2-Watt-Black-Outdoor-Integrated-LED-Landscape-Path-Light-CY2001-08W%2F300862401%3Fcm_mmc%3DCJ-_-1122587-_-1225267-_-Home%252520Depot%252520Product%252520Catalog
Location: http://www.amazon.com/gp/redirect.html?ascsubtag=c5adbaec22a211e7ba55fad51a7f68bf0INT&ie=UTF8&tag=slicinc-20&linkCode=ur2&camp=1789&creative=9325&location=https%3A%2F%2Fwww.amazon.com%2Fdp%2FB002R5ARDG%3Ftag%3Dslicinc-20%26ascsubtag%3Dc5adbaec22a211e7ba55fad51a7f68bf0INT%26smid%3DATVPDKIKX0DER
Location: http://linksynergy.walmart.com/fs-bin/click?u1=c5ecc1f622a211e78db83a6842ae87b90INT&id=UbUihDh2awY&subid=&offerid=223073.1&type=10&tmpid=273&RD_PARM1=https%253A%252F%252Fwww.walmart.com%252Fip%252FFisher-Price-Tough-Trike-Camo%252F52291447
Location: http://click.linksynergy.com/fs-bin/click?u1=c62de25822a211e7a8d2368abb8ad1ae0INT&id=lw9MynSeamY&subid=&offerid=321325.1&type=10&tmpid=14378&RD_PARM1=http%3A%2F%2Fwww.shoebuy.com%2Fclarks-kyros-plain-toe-lace-up-shoe%2F802859%2F1732550
Location: http://go.redirectingat.com/?id=355X561&test=off&xcust=c66fc50622a211e7aeba6aab85d728c40INT&url=https%3A%2F%2Fwww.foxconnect.com%2Fheat-director-s-definitive-edition.html
Location: http://go.redirectingat.com/?id=355X561&test=off&xcust=c6adbbc222a211e78c6ad690076ceda90INT&url=https%3A%2F%2Fstarbucks.promo.eprize.com%2Fspring%2F
```

**Comment by sblask** [comment]
@kerframil The URLs you posted here seem to be handled fine by this add-on though. So what you are saying is that something like "https://slickdeals.net/?adobeRef=9d24ee201d5611e79c4756e88f83325f0001&pno=278320&lno=1&trd=Home%2BDepot&afsrc=1" gives a 302 to `http://go.redirectingat.com/?id=355X561&test=off&xcust=c6adbbc222a211e78c6ad690076ceda90INT&url=https%3A%2F%2Fstarbucks.promo.eprize.com%2Fspring%2F`? There is no way to skip the request that causes the initial 302, but this add-on would skip one redirect and go to starbucks... instead of redirectingat...

**Comment by kerframil** [comment]
@sblask Yes. What @Aromendal wants is impossible. At best, the Location that accompanies the initial response could be sanitised. Currently, this doesn't happen. I tested by observing the developer console and using an independent packet sniffer. This is with Firefox 52.0.2, in case it matters. Not that I'm complaining; it's just an observation.
