### ISSUE TITLE
[rules request] download links for CNET apps

### ISSUE THREAD

**Issue by EMLVIRUS** [sblask/firefox-skip-redirect#16]
On page: http://download.cnet.com/Advanced-SystemCare-Free/3000-2086_4-10407614.html?part=dl-&subj=dl&tag=button

e.g. :
http://dw.cbsi.com/redir?ttag=download_now_button_click&lop=link&ptid=3000&pagetype=product_detail_bp&astid=2&edid=3&tag=button&siteid=4&destUrl=http%3A%2F%2Fdownload.cnet.com%2FAdvanced-SystemCare-Free%2F3001-2086_4-10407614.html%3Fpart%3Ddl-&onid=2086&oid=3000-2086_4-10407614&rsid=cbsidownloadcomsite&sl=en&sc=us&topicguid=utilities%2Fdiagnostic&topicbrcrm=&pid=15734734&mfgid=6271865&merid=6271865&ctype=dm&cval=NONE&ltype=dl_dlnow&spi=fb7c6120785a9f80fc950a26f81e59b6&devicetype=desktop&pguid=cb82f51729851766eb525292&viewguid=jbFBQu22bkBGbzj8aSqacEvG4hhq8nn0ux-a

destination:
http://download.cnet.com/Advanced-SystemCare-Free/3001-2086_4-10407614.html?part=dl-

**Comment by sblask** [comment]
I have an explicit rule to not skip redirects for URLs containing download and others (https://github.com/sblask/firefox-skip-redirect/blob/master/lib/url.js#L9) because it leads to problems in many cases...

**Comment by EMLVIRUS** [comment]
In this case, it should not case actual problem. And dw.cbsi.com is listed in many tracking list.
Could you add an exception?

**Comment by sblask** [comment]
What do you mean by tracking list? Something like uBlock? Not sure that Skip Redirect will work for it in that case. I have no control over which extension gets to do it's thing first, so if blocking happens before skipping, then I can't do anything about it.

I will probably make a few changes at some point, but it might take a while...

**Comment by EMLVIRUS** [comment]
What I mean is that you should process this redirection as dw.cbsi.com is a tracker host (so it is listed is tracking list).

**Comment by sblask** [comment]
I just uploaded a new beta to https://addons.mozilla.org/en-US/firefox/addon/skip-redirect/ (Development Channel at the bottom). Would you mind having a look and letting me know how it goes? At least the example you gave here seems to work without changing the preferences.

**Comment by EMLVIRUS** [comment]
fix confirmed. thx😀
