### ISSUE TITLE
Regular Express How to allow all except match

### ISSUE THREAD

**Issue by DarKWinGTM** [sblask/firefox-skip-redirect#17]
How i can write reg to all web can redirect but not google.com,adexchangeprediction.com ?

\b(?!(google.com)|(adexchangeprediction.com))\b\S+

**Comment by sblask** [comment]
It should be enough to add `google.com|adexchangeprediction.com` to the exceptions. (If you don't need a regexp, which you don't seem to, this will be the easiest)

**Comment by DarKWinGTM** [comment]
if i config "google.com|adexchangeprediction.com" it mean block all except google.com,adexchangeprediction.com

I need allow all but block in list

**Comment by sblask** [comment]
No? If you configure `google.com|adexchangeprediction.com` as exception, no redirecting will take place for URLs containing `google.com` or `adexchangeprediction.com`, but for all others apart from some exceptions that are known to cause problems.

**Comment by DarKWinGTM** [comment]
It's mean skip redirect all but not in exceptions list

user_pref("extensions.skipredirect.exceptions", "histock.info|onclickads.net|onclkds.com|sabavision.com|shiek1ph.com|urldelivery.com|poptm.com");

I want to known how to opposite exceptions list ?

**Comment by sblask** [comment]
If I understand properly, you want redirects to happen only for URLs that you configure. This is not currently possible, but I might implement it at some point in the future.
