### ISSUE TITLE
request: blacklist mode

### ISSUE THREAD

**Issue by TheRealMarnes** [sblask/firefox-skip-redirect#2]
I think it would be a good idea to add an optional blacklist mode instead of the current built-in whitelist mode. Basically, the addon would stop trying to look for possible redirects on every load except when the url matches a filter, and instead only look for a redirect on urls matching the given filters. This minimizes breakage on various sites (which are an unknown) and instead fixes redirects only on sites the (power)user decides to add to his list. The blacklist can simply be a list of the host sites' domains. The built-in whitelist that prevents known breakages could still be applied just to be sure.

I could try to write an implementation myself if you like.

**Comment by sblask** [comment]
I thought about this myself, but as I won't use it, I waited for a request before thinking about it.

But first of all, I think the notion is wrong, which was also one thing that confused me a lot with Redirect Cleaner. I consider the currently implemented mode as blacklist: skip for every page but the given exceptions. So to me it would be a whitelist mode you are suggesting: do not skip unless the url matches the given exceptions?

Would you agree that the choice between blacklist and whitelist mode is fundamental? I don't think it makes a lot of sense to switch often between the two as you could with Redirect Cleaner. I would start with the blacklist mode and when I see there are just too many problems/exceptions, I would switch over to whitelist mode. So I would not go the same way as redirect cleaner:

   - the toolbar button will always be enable/disable and not switching modes
   - the switch between blacklist/whitelist would be in the preferences
   - there would be only one list of exceptions that is used according to the mode

I would also not use the built in blacklist(login etc.). It's not a list of things that are certain to cause problems, but more of a guess. To me, the whitelist mode is about giving full control to the user. So whenever something doesn't work(as in it: redirects too much), it's the users problem.

What do you think?

**Comment by TheRealMarnes** [comment]
> But first of all, ...
Yes to this whole paragraph. The wording always gets me too, it's a matter of style really.

It doesn't make much sense to switch all the time indeed. You'd switch between modes very rarely or even only once.
> the toolbar button will always be enable/disable and not switching modes
Yes
> the switch between blacklist/whitelist would be in the preferences
Yes
> there would be only one list of exceptions that is used according to the mode
Maybe, but rather not... I can see the point, but the user will essentially have 2 unrelated lists at hand: one for the current mode with exception filters, and the new one with a list of domains to work on. The two aren't interchangeable or similar at all, so it seems cleaner to keep them in different textboxes. When the user switches to the other mode to see if it works better, they don't have to lose their current list by replacing it with the other. Each mode just gets its own dedicated list so that switching back if need be is effortless.

> I would also not use the built in blacklist(login etc.)
Yes and no. It is safer to leave it to the user entirely (what if one of your filters actually prevents it from working for them, for example?), but on the other hand it is convenient and saves time. The way I do this in one of my addons is to make a read-only pref field containing a built-in list the user can see and copy, with a switch to (de)activate it, and a second editable text field they can write their own filters in. They can either stick to default and enjoy no-frills "good enough" setup, or switch it off, copy the parts they need and customize to their liking. I made my own sdk module specifically for making this fancy pref field system easy.

**Comment by sblask** [comment]
I wished simple-prefs would just be a tiny bit more powerful(no way to reset to default value is really bugging me). If I could disable one of the lists depending on the mode, that would solve all my problems... This readonly field, how do you do that? Would you mind sharing this sdk module you mentioned?

**Comment by TheRealMarnes** [comment]
A readonly pref is simply
```javascript
prefs.on("prefName", pref => prefs.prefs[pref] = defaultValue);
```
The default value is also set on init by the code instead of package.json so it's all in one place with a const.

I use some "fancy"prefs in this addon:
https://addons.mozilla.org/en-US/firefox/addon/url-manager/
https://github.com/TheRealMarnes/url-manager

https://github.com/TheRealMarnes/url-manager/blob/master/src/lib/validate-prefs-1.0.2.js
https://github.com/TheRealMarnes/url-manager/blob/master/src/index.js#L60

usage:
```javascript
const {validatePref} = require("./lib/validate-prefs-1.0.2.js");
// validatePref(x, y, z);
// x: pref name, y: true/false validity test, z: callback
validatePref("prefName", value => testValidity(value), (valid, value) => {
	if (valid) updateSettings(value);
});

It automatically sets a checkbox called <prefname>Valid to true and false based on the validity test on every edit.

```json
"preferences": [{
		"name": "removeValid",
		"title": "Valid removal list?",
		"type": "bool",
		"value": true
	},
	{
		"name": "remove",
		"title": "Removal list",
		"type": "string",
		"value": ""
	}]
```

I think just playing with that addon's prefs and reading the code will explain things a lot more than if I try to write it out :P

**Comment by TheRealMarnes** [comment]
Now I remember what I felt like what I was forgetting in my last post: the callback for validatePref can also return a value that will overwrite the current pref. This lets you make a pref readonly as well:
`validatePref("prefName", value => true, (valid, value) => defaultValue);`

**Comment by sblask** [comment]
I just uploaded a new beta to https://addons.mozilla.org/en-US/firefox/addon/skip-redirect/ (Development Channel at the bottom). Would you mind having a look and letting me know how it goes?

**Comment by TheRealMarnes** [comment]
Sorry, I stopped using firefox...

**Comment by sblask** [comment]
Fair enough. It's an embedded webextension today, but once released as a webextension, you should be able to use it in Chrome and others. I can let you know if you are interested...

**Comment by TheRealMarnes** [comment]
Hmm, why not, thanks :)

**Comment by sblask** [comment]
Here you go: https://chrome.google.com/webstore/detail/skip-redirect/jaoafjdoijdconemdmodhbfpianehlon
