### ISSUE TITLE
Quick add last redirected to the blacklist

### ISSUE THREAD

**Issue by jtojnar** [sblask/firefox-skip-redirect#23]
The new pop up is great but it could be even better if clicking it would open the Skip Redirect compartment and allow to add the URL to the list in one click.

**Comment by sblask** [comment]
I think it would be better if I could simply copy the URL and then click on the toolbar icon to edit the options manually. But any way, there is currently no support for adding buttons to the notification and listen to clicks :-(

**Comment by sblask** [comment]
I found a way. I added a context menu entry to the toolbar icon to copy the last skipped URL. Firefox version just waiting for review. Available for Chrome within the hour...

**Comment by jtojnar** [comment]
Nice, did not know about this possibility.

I was working on adding it to the popup but did not finish the regex extraction.

https://github.com/sblask/webextension-skip-redirect/compare/master...jtojnar:add-last?expand=1

**Comment by sblask** [comment]
My solution is similar: https://github.com/sblask/webextension-skip-redirect/commit/b83cc7c84a1de96baedad1e5ff564a65d3672051 I didn't think about persisting the URL, but that might be unnecessary.

Adding stuff to the clipboard is a bit more complicated then expected though. But I still think copying and then editing the blacklist manually is the way to go. Adding stuff to the blacklist automatically will be very hard I think. Where to cut off the URL? If you only remove the target URL, there might still be something not generic left in the querystring or path. Like an ID which would make it fail the next time. If you only use the domain, you might block too much...

**Comment by jtojnar** [comment]
I persist the URL just as a way to transfer it from the content script to the popup, it is not necessary when using `executeScript`. Creating the regex is indeed hard, which is why I open the options to allow user to fine-tune the regex. User probably wants to add it to the list anyway so this will save him two steps.

**Comment by sblask** [comment]
If you want to want to add it to the options anyway, you could just modify the blacklist preference directly and will be available in the options dialog.

It's not really possible to bring up the options popup though. You can click the button or you can do it through the context menu by providing `commands`. The latter is not Chrome compatible though...
