### ISSUE TITLE
jpm: icon issue

### ISSUE THREAD

**Issue by TheRealMarnes** [sblask/firefox-skip-redirect#3]
The latest update added a known problem: the addon icon breaks.

https://bugzilla.mozilla.org/show_bug.cgi?id=1141839

To fix it, install.rdf needs to be edited after "jpm xpi" to remove the icon entry, and icon.png needs to be added to the addon's root.

Edit: same issue on another addon, for reference: https://github.com/antoyo/auto-sort-bookmarks/issues/22

**Comment by TheRealMarnes** [comment]
Please upvote the bug too please, mozilla doesn't care enough yet, maybe if it gets more votes...

**Comment by sblask** [comment]
Not sure the icon is the issue,  seems like fucked up the release(see #4).  Anyway,  there is a workaround for the icon path that I use here too: https://github.com/sblask/firefox-simple-form-fill I'll make sure it works before making another release...

**Comment by TheRealMarnes** [comment]
I see what you did there :P Feels kinda icky to me though, putting the url you expect to see after compilation into the source you compile in the first place. Kinda like breaking encapsulation.

**Comment by sblask** [comment]
There was actually a problem with the icon. While fixing I also changed it to only use svg now. Will be in version 1.0.2 which is now awaiting Mozilla's review. The workaround wasn't my idea, it's documented here: https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/package_json

Not sure it's related to your bug in bugzilla, but I could not use relative urls for the icon in the button description, it had to be a self.data url...
