### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by Peuj** [sblask/firefox-skip-redirect#4]
Hi,

After installing version 1.0.1:

fileName :"resource://skipredirect-at-sblask/index.js"
lineNumber :5
message :"Module `./ui` is not found at resource://skipredirect-at-sblask/ui.js"
stack :"@resource://skipredirect-at-sblask/index.js:5:12
run@resource://gre/modules/commonjs/sdk/addon/runner.js:145:19
startup/</<@resource://gre/modules/commonjs/sdk/addon/runner.js:86:7
Handler.prototype.process@resource://gre/modules/Promise-backend.js:922:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise-backend.js:801:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise-backend.js:740:39
"

Thanks

**Comment by fraff** [comment]
Hi, and thanks for this extension,

Got same problem here, firefox 38.3 on debian wheezy.

**Comment by sblask** [comment]
Sorry about that,  I thought I had changed only one line,  but forgot about other stuff I changed earlier. Can't fix it right now, but will as soon as I can. Hopefully tomorrow...

**Comment by sblask** [comment]
Will be fixed in version 1.0.2 which is now awaiting Mozilla's review.
