### ISSUE TITLE
Problem in Private mode

### ISSUE THREAD

**Issue by Peuj** [sblask/firefox-skip-redirect#6]
Hi,

I don't the see the icon in private mode.
It seems the extraction of the final URL works anyway.

Thanks

**Comment by sblask** [comment]
Seems like I don't have the permission for private mode enabled, so you not only don't see the icon, but skipping should also not work. I will enable the permission when I find the time...

**Comment by Peuj** [comment]
This is what I suspected, I didn't look at your code before to post the issue.
In case you don't know, you simply need to add this line in the file package.json

"permissions": {"private-browsing": true}

**Comment by sblask** [comment]
A new version just came through review, it should work now.
