### ISSUE TITLE
Problem/suggestion: remove hardcoded logging

### ISSUE THREAD

**Issue by TheRealMarnes** [sblask/firefox-skip-redirect#7]
The code now has a couple of console.log statements that are always executed. Example: https://github.com/sblask/firefox-skip-redirect/blob/master/index.js#L29

I'd suggest replacing these console.log statements with something like debug in https://github.com/TheRealMarnes/doubleclick-image-downloader/blob/master/src/index.js#L17
And adding a boolean pref accordingly to the prefs list to make it work.

Didn't the AMO mods complain about this? They release all hell on me if I leave a hardcoded logging statement somewhere that isn't behind a pref. It's nicer for the user to open a console for a problem and not be swamped with output they don't need at the time (in fact I'm bringing this up because I saw the output all over my console).

**Comment by sblask** [comment]
They did complain and I complained back, because that is what log levels are for: https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/console#Setting_the_Logging_Level If you see something in your console, it means that you either enabled logging, or that there is a bug in Firefox...

**Comment by TheRealMarnes** [comment]
Well yeah, technically, but it's not a very user-friendly solution. Even for me as a dev, I find it annoying to open my console and get swarmed with loads of output I did not ask for when trying to find something specific. SDK addons at least have the about:config pref to disable their output, but that's pretty user-unfriendly already, and other addons don't even have such a system. It's just good practice to put a checkbox on addons to toggle all logging, and doesn't really make the coding more complicated.

**Comment by sblask** [comment]
So far, the logging is only for me, but it is good to have it in place in case there is a bug I can't reproduce. If I were to add a preference, then I would still use the extensions.extensionID.sdk.console.logLevel as a means to do that. Ideally, that would be implemented by Firefox so addon developers don't have to do it themselves. I currently don't want to spend a log of effort on my addons because I feel like I have to redo everything at some point anyway because of web extensions :-(

**Comment by TheRealMarnes** [comment]
Yeah... Ideally, it should be, but knowing mozilla and their development attitude of lately, it's never gonna happen. And I'm not sure what to do with my addons atm either, besides just fixing smaller issues people report. I wanna get off this ride before it crashes (I hate where mozilla is going with firefox), but moving to palemoon or chrome are not solutions either...

**Comment by sblask** [comment]
As long as reviews still pass with the logging, I will just keep this closed...
