### ISSUE TITLE
Problem/Suggestion : file protocol

### ISSUE THREAD

**Issue by zymase** [sblask/firefox-skip-redirect#8]
Hi,

_Skip Redirect 1.05_ on _Firefox 44.0.1 64-BIT_ running flawlessly. True pleasure.

**One suggestion**:
I see that Skip Redirect handles the "ftp", "http", "https", "mms", "rtsp" protocols.
Could it handle the "_file_" protocol as well?

**Example**:
I'm using _Sage_  (_Firefox_ add-on) as my RSS Feed Reader. It displays feeds in the _file_ format.
Some links will include redirects, for instance,
> https://www.bing.com/news/apiclick.aspx?ref=xxxxx&url=LINK

In that case _Skip Redirect_ is not programmed to interfere.

T

**Comment by sblask** [comment]
Is Sage still working? The last couple of reviews are not very encouraging. So I rather not try myself. So what you are saying is that `LINK` will start with `file://`? I that's the only thing, it would be a one line addition here: https://github.com/sblask/firefox-skip-redirect/blob/master/lib/url.js#L25 But I don't quite understand why a `bing.com` link would have a `file://` in it, does Sage do some magic there? (Again, I didn't try.)

**Comment by zymase** [comment]
I'm using _Sage++ (Higmmer's Edition)_ Installation Page which has no AMO page, available at 
> http://blog-imgs-30-origin.fc2.com/h/i/m/himag/sagepp-higmmersedition-install.html

The add-on is **signed** and runs great, always updated.

Concerning the file issue, perhaps I haven't been precise enough.
Bing News RSS is : 
> https://www.bing.com/news/search?q=&format=RSS

Sage++ displays this url here on Firefox in a tab: 
> file:///[MY PROFILE]/chrome/sagepp/sagepp.html

The links don't change, they are of the form:
> https://www.bing.com/news/apiclick.aspx?ref=xxxxx&url=LINK

But, as I understand it, the link being on a file: page, Skip Redirect doesn't handle it, or am I missing somethin

**Comment by sblask** [comment]
Fixed with version 1.0.6, currently under review by Mozilla
